USE ecom_sales;
SELECT * FROM  sales_data;


-- 1. Which category generates highest revenue?
SELECT 
    category, 
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM sales_data
GROUP BY category
ORDER BY highest_revenue DESC;


-- 2. Are discounts actually increasing purchase value?
SELECT 
    discount_applied, 
    ROUND(SUM(purchase_amount), 2) AS total_revenue, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM sales_data
GROUP BY discount_applied;

-- Business Problem: Discount may reduce profit without increasing sales
-- Impact:-

-- --Identify effectiveness of discounts

-- --Reduce unnecessary discount costs

-- --Improve profit margins


-- 3.What is the total revenue generated by male and female customer.

SELECT 
    gender, 
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM sales_data
GROUP BY gender
ORDER BY highest_revenue DESC;


-- --? Business Problem: Lack of understanding of revenue contribution by gender segments.
-- --Impact:-

-- --Helps design targeted marketing campaigns -Improves customer segmentation strategy

-- --Enhances personalization efforts


-- 4. Which customer used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount, 
    discount_applied
FROM sales_data
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM sales_data)
LIMIT 10;

-- Business Problem: Company cannot identify high-spending customers who are also discount users.


-- 5. Which are the top/bottom 5 products with the highest/lowest average review rating?

-- Top 5 products
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS Avg_ratings
FROM sales_data
GROUP BY item_purchased
ORDER BY Avg_ratings DESC
LIMIT 5;

-- Bottom 5 products
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS Avg_ratings
FROM sales_data
GROUP BY item_purchased
ORDER BY Avg_ratings ASC
LIMIT 5;


-- 6..avg purchase:standard vs express shipping.
SELECT 
    shipping_type, 
    COUNT(DISTINCT customer_id) AS order_placed, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase, 
    ROUND(SUM(purchase_amount), 2) AS revenue
FROM sales_data
GROUP BY shipping_type
ORDER BY revenue DESC;
-- Business Problem: Unclear if faster shipping leads to higher spend.alter


-- 7. Do subscribed customers spend more? Compare average spend and total revenue between subscription statuses
SELECT 
    subscription_status, 
    COUNT(customer_id) AS users, 
    ROUND(AVG(purchase_amount), 2) AS avg_revenue, 
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM sales_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- --? Business Problem: The effectiveness of subscription programs is unknown.
-- Impact
-- --Validates subscription model performance
-- --Improves customer loyalty programs
-- --Increases customer lifetime value (CLV)


-- 8. Top 5 products with highest discount usage %
SELECT 
    item_purchased, 
    COUNT(item_purchased) AS total_number_of_times_sold,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS number_of_times_sold_when_discount_applied,
    (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)) AS discount_percent
FROM sales_data
GROUP BY item_purchased
ORDER BY discount_percent DESC
LIMIT 5;


-- ? Business Problem:Some products may be overly dependent on discounts.
-- -Impact:-
-- --Identifies discount-driven products
-- -Helps optimize pricing strategy
-- --Reduces profit margin loss



-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase,
-- -and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM sales_data
GROUP BY 
    CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END;

-- Business Problem: Lack of customer segmentation leads to generic strategy.


-- 10. What are the top 3 most purchased products within each category?
WITH CTE AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(item_purchased) AS most_purchased,
        RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
    FROM sales_data
    GROUP BY category, item_purchased
)
SELECT * FROM CTE 
WHERE RNK <= 3;

-- Business Problem: The company doesn't know top-performing products within categories.


-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to be subscribed?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY 
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat Buyers'
            ELSE 'Normal Buyers'
        END), 2) AS percents
FROM sales_data
GROUP BY 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END, 
    subscription_status;

-- Business Problem: Unclear relationship between loyalty and subscription.

-- 12. What is the revenue contribution of each age group?
SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '35-50'
        ELSE '51+'
    END AS age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM sales_data
GROUP BY 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '35-50'
        ELSE '51+'
    END
ORDER BY total_revenue DESC;

-- ? Business Problem: No visibility into which age group contributes most to revenue.
-- Impact:-
-- --Enables age-based targeting
-- --Enhances marketing efficiency